## Polar night (dark -> bright)
#nord0 #2e3440
#nord1 #3b4252
#nord2 #434c5e
#nord3 #4c566a
#
## Snow storm (dark -> bright)
#nord4 #d8dee9
#nord5 #e5e9f0
#nord6 #eceff4
#
## Frost
#nord7 #8fbcbb
#nord8 #88c0d0
#nord9 #81a1c1
#nord10 #5e81ac
#
## Aurora
#nord11 #bf616a
#nord12 #d08770
#nord13 #ebcb8b
#nord14 #a3be8c
#nord15 #b48ead


# Dark
foreground            #d8dee9
background            #2e3440
selection_foreground  #d8dee9
selection_background  #3b4252

mark1_foreground #d08770
mark2_foreground #d08770
mark3_foreground #d08770

url_color #e5e9f0

# Cursor colors
cursor            #d8dee9
cursor_text_color #4c566a

# Tab bar colors
active_tab_foreground   #e5e9f0
active_tab_background   #4c566a
inactive_tab_foreground #d8dee9
inactive_tab_background #3b4252

# black (nord1 / nord3)
color0  #3b4252
color8  #4c566a

# red (nord11)
color1  #bf616a
color9  #bf616a

# green (nord14)
color2  #a3be8c
color10 #a3be8c

# yellow (nord13)
color3  #ebcb8b
color11 #ebcb8b

# blue (nord9)
color4  #81a1c1
color12 #81a1c1

# magenta (nord15)
color5  #b48ead
color13 #b48ead

# cyan (nord8)
color6  #88c0d0
color14 #88c0d0

# white (nord5)
color7  #e5e9f0
color15 #e5e9f0


font_family	JetBrains Mono NL
font_size 14

# - Use additional nerd symbols
# https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points
symbol_map U+E5FA-U+E62B Symbols Nerd Font Mono
# Devicons
symbol_map U+e700-U+e7c5 Symbols Nerd Font Mono
# Font Awesome
symbol_map U+f000-U+f2e0 Symbols Nerd Font Mono
# Font Awesome Extension
symbol_map U+e200-U+e2a9 Symbols Nerd Font Mono
# Material Design Icons
symbol_map U+f0001-U+f1af0 Symbols Nerd Font Mono
# Weather
symbol_map U+e300-U+e3e3 Symbols Nerd Font Mono
# Octicons
symbol_map U+f400-U+f532 Symbols Nerd Font Mono
symbol_map U+2665 Symbols Nerd Font Mono
symbol_map U+26A1 Symbols Nerd Font Mono
# [Powerline Symbols]
symbol_map U+e0a0-U+e0a2 Symbols Nerd Font Mono
symbol_map U+e0b0-U+e0b3 Symbols Nerd Font Mono
# Powerline Extra Symbols
symbol_map U+e0b4-U+e0c8 Symbols Nerd Font Mono
symbol_map U+e0cc-U+e0d4 Symbols Nerd Font Mono
symbol_map U+e0a3 Symbols Nerd Font Mono
symbol_map U+e0ca Symbols Nerd Font Mono
# IEC Power Symbols
symbol_map U+23fb-U+23fe Symbols Nerd Font Mono
symbol_map U+2b58 Symbols Nerd Font Mono
# Font Logos (Formerly Font Linux)
symbol_map U+f300-U+f32f Symbols Nerd Font Mono
# Pomicons
symbol_map U+e000-U+e00a Symbols Nerd Font Mono
# Codicons
symbol_map U+ea60-U+ebeb Symbols Nerd Font Mono
# Heavy Angle Brackets
symbol_map U+276c-U+2771 Symbols Nerd Font Mono
# Box Drawing
symbol_map U+2500-U+259f Symbols Nerd Font Mono

# cursor_shape beam
cursor_trail 1

confirm_os_window_close 0

shell fish

map ctrl+c copy_or_interrupt
